### ISSUE TITLE
Updating to latest version fails leaving broken vscode dev environment - can no longer debug

### ISSUE THREAD

**Issue by stemixreal** [Azure/azure-functions-core-tools#2544]
Hi Folks,

I'm having a few issues updating core tools. After updating npm to 7.9 (6.x silently failed), this is the latest error in a series of errors while trying to install the latest update (3.0.3442) when prompted (on every start-up) in vscode:

```
14:44:49: Running command: "npm install -g azure-functions-core-tools@3"...
npm ERR! code 1
npm ERR! path C:\Users\dev\AppData\Roaming\npm\node_modules\azure-functions-core-tools
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node lib/install.js
npm ERR! internal/modules/cjs/loader.js:883
npm ERR!   throw err;
npm ERR!   ^
npm ERR! 
npm ERR! Error: Cannot find module 'unzipper'
npm ERR! Require stack:
npm ERR! - C:\Users\dev\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\install.js
npm ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
npm ERR!     at Module.require (internal/modules/cjs/loader.js:952:19)
npm ERR!     at require (internal/modules/cjs/helpers.js:88:18)
npm ERR!     at Object.<anonymous> (C:\Users\dev\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\install.js:3:18)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:1063:30)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:928:32)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\lib\\install.js'
npm ERR!   ]
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dev\AppData\Local\npm-cache\_logs\2021-04-09T13_44_51_843Z-debug.log
```

Running:  **npm ls -g azure-functions-core-tools** gives
C:\Users\dev\AppData\Roaming\npm       
└── azure-functions-core-tools@3.0.3442

Everything is broken including the new integrated debugging tools. All I have done is try to install the update in line with guidelines in the March Functions Live webcast by @anthonychu & @jeffhollan 

This isn't a new project. Dev environment was fine. I've got several SWAs with apis deployed and working ok. The problems began when I tried to update the tools. Whatever I do, the installed func version remains at 3.0.2996 even though it looked as if the latest has been installed. I've restarted vscode, rebooted, tried installing 3.0.3388 first, installed from command line as well as from vscode.

This is quite urgent for me so would appreciate any suggestions that might help resolve this.

cheers

**Comment by stemixreal** [comment]
Phew. Fixed it. 

The 3.0.2996 version was installed by myself (don't recall what I did) or some process whch was available to uninstall in settings-apps. It seems that version was being picked up by vscode regardless of anything i did on the command line or in a vscode terminal.

Once I uninstalled that and reinstalled vscode things appeared ok on the surface but I also had to change the default port in launch.json from 9229 to something else then restart vscode as I was getting a - port in-use/access denied error

**Comment by MJECloud** [comment]
Like i commented [here](https://github.com/Azure/azure-functions-core-tools/issues/2526#issuecomment-817035927),  i also had to reinstall the core tools.

**Comment by apawast** [comment]
@stemixreal @MJECloud glad you were able to resolve it, but we'd like to understand the issue further. What version of node and npm are you using?

**Comment by stemixreal** [comment]
Hii @apawast , initially I was using node 6.x (not 100% which version but it has been working fine so I hadn't updated for perhaps 6 months) Now I'm using the latest version which I upgraded to after I'd encountered problems and failed to fix them.

Versions:
Npm - 7.9.0
Node 14.15.0

The problem for me was that no matter what I did, un/install in vscode it picked up the wrong version until I uninstalled the version that was probably installed via an msi (vague memory of possibly doing something like that).

It looks like a bug to me because the update is completing as if successful but still picks up an old version. It could easily be something I did wrong though

**Comment by MJECloud** [comment]
@apawast I'm currently using following versions 
Node: 15.14.0
Npm: 7.7.6

**Comment by fabiocav** [comment]
@MJECloud we're working on planning and assignment and it would be good to understand the OS you were using when you ran into this issue. Can you please share that information and whether you've observed this in multiple machine OS configurations? Thanks!

**Comment by stemixreal** [comment]
Hi @fabiocav,

Sorry for the delay replying.

OS is windows 10 pro v2004
build 1904.1110
Experience: WFEP 120.2212.3530.0


Tried a few times to resolve this. Updating to most recent version, I still have the problem. Never fixed it it seems, I just bypassed it by reinstalling. I try every new release but always the same problem - I haven't been able to update the tools since I reinstalled things to apply the 3.0.3442 update. I don't have the will to reinstall on every update, gets old quickly.

It seems to be the same issue. It must have something to do with my environment right? Below are the logs. Unzipper is specified as the issue as before but fix that (even though it exists) and then other stuff breaks so any ideas are welcome greatly appreciated.  

Thanks.

--- debug.log
0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'install',
0 verbose cli   '-g',
0 verbose cli   'azure-functions-core-tools@3'
0 verbose cli ]
1 info using npm@7.9.0
2 info using node@v14.15.0
3 timing npm:load:whichnode Completed in 5ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:C:\Users\dev\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 14ms
6 timing config:load:builtin Completed in 15ms
7 timing config:load:cli Completed in 3ms
8 timing config:load:env Completed in 2ms
9 timing config:load:file:C:\Users\dev\AppData\Local\Temp\.npmrc Completed in 0ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:c:\users\dev\.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:C:\Users\dev\AppData\Roaming\npm\etc\npmrc Completed in 1ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setEnvs Completed in 2ms
17 timing config:load Completed in 29ms
18 timing npm:load:configload Completed in 29ms
19 timing npm:load:setTitle Completed in 0ms
20 timing npm:load:setupLog Completed in 1ms
21 timing npm:load:cleanupLog Completed in 5ms
22 timing npm:load:configScope Completed in 0ms
23 timing npm:load:projectScope Completed in 1ms
24 timing npm:load Completed in 42ms
25 timing config:load:flatten Completed in 6ms
26 timing arborist:ctor Completed in 1ms
27 timing idealTree:init Completed in 21ms
28 timing idealTree:userRequests Completed in 11ms
29 silly idealTree buildDeps
30 silly fetch manifest azure-functions-core-tools@3
31 http fetch GET 200 https://registry.npmjs.org/azure-functions-core-tools 6735ms
32 silly placeDep ROOT azure-functions-core-tools@3.0.3568 OK for:  want: 3
33 silly fetch manifest chalk@3.0.0
34 silly fetch manifest command-exists@1.2.8
35 silly fetch manifest glob@7.1.6
36 silly fetch manifest https-proxy-agent@5.0.0
37 silly fetch manifest progress@2.0.3
38 silly fetch manifest rimraf@3.0.2
39 silly fetch manifest tmp@0.1.0
40 silly fetch manifest unzipper@0.10.10
41 http fetch GET 200 https://registry.npmjs.org/rimraf 530ms
42 http fetch GET 304 https://registry.npmjs.org/command-exists 540ms (from cache)
43 http fetch GET 304 https://registry.npmjs.org/unzipper 1366ms (from cache)
44 http fetch GET 304 https://registry.npmjs.org/glob 1388ms (from cache)
45 http fetch GET 200 https://registry.npmjs.org/chalk 1406ms
46 http fetch GET 304 https://registry.npmjs.org/https-proxy-agent 1415ms (from cache)
47 http fetch GET 304 https://registry.npmjs.org/progress 1438ms (from cache)
48 http fetch GET 304 https://registry.npmjs.org/tmp 1436ms (from cache)
49 timing idealTree:#root Completed in 8244ms
50 timing idealTree:buildDeps Completed in 8246ms
51 timing idealTree:fixDepFlags Completed in 2ms
52 timing idealTree Completed in 8281ms
53 timing reify:loadTrees Completed in 8403ms
54 silly reify mark deleted [
54 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\agent-base'
54 silly reify ]
55 silly reify mark deleted [
55 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\ansi-styles'
55 silly reify ]
56 silly reify mark deleted [
56 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\big-integer'
56 silly reify ]
57 silly reify mark deleted [
57 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\balanced-match'
57 silly reify ]
58 silly reify mark deleted [
58 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\brace-expansion'
58 silly reify ]
59 silly reify mark deleted [
59 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\bluebird'
59 silly reify ]
60 silly reify mark deleted [
60 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\buffer-indexof-polyfill'
60 silly reify ]
61 silly reify mark deleted [
61 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\buffers'
61 silly reify ]
62 silly reify mark deleted [
62 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\chainsaw'
62 silly reify ]
63 silly reify mark deleted [
63 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\chalk'
63 silly reify ]
64 silly reify mark deleted [
64 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\color-convert'
64 silly reify ]
65 silly reify mark deleted [
65 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\concat-map'
65 silly reify ]
66 silly reify mark deleted [
66 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\color-name'
66 silly reify ]
67 silly reify mark deleted [
67 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\core-util-is'
67 silly reify ]
68 silly reify mark deleted [
68 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\binary'
68 silly reify ]
69 silly reify mark deleted [
69 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\debug'
69 silly reify ]
70 silly reify mark deleted [
70 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\fs.realpath'
70 silly reify ]
71 silly reify mark deleted [
71 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\graceful-fs'
71 silly reify ]
72 silly reify mark deleted [
72 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\fstream'
72 silly reify ]
73 silly reify mark deleted [
73 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\glob'
73 silly reify ]
74 silly reify mark deleted [
74 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\https-proxy-agent'
74 silly reify ]
75 silly reify mark deleted [
75 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\has-flag'
75 silly reify ]
76 silly reify mark deleted [
76 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\inherits'
76 silly reify ]
77 silly reify mark deleted [
77 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\inflight'
77 silly reify ]
78 silly reify mark deleted [
78 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\listenercount'
78 silly reify ]
79 silly reify mark deleted [
79 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\isarray'
79 silly reify ]
80 silly reify mark deleted [
80 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\minimatch'
80 silly reify ]
81 silly reify mark deleted [
81 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\minimist'
81 silly reify ]
82 silly reify mark deleted [
82 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\ms'
82 silly reify ]
83 silly reify mark deleted [
83 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\mkdirp',
83 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\.bin\\mkdirp',
83 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\.bin\\mkdirp.cmd',
83 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\.bin\\mkdirp.ps1'
83 silly reify ]
84 silly reify mark deleted [
84 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\path-is-absolute'
84 silly reify ]
85 silly reify mark deleted [
85 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\once'
85 silly reify ]
86 silly reify mark deleted [
86 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\progress'
86 silly reify ]
87 silly reify mark deleted [
87 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\process-nextick-args'
87 silly reify ]
88 silly reify mark deleted [
88 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\readable-stream'
88 silly reify ]
89 silly reify mark deleted [
89 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\rimraf',
89 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\.bin\\rimraf',
89 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\.bin\\rimraf.cmd',
89 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\.bin\\rimraf.ps1'
89 silly reify ]
90 silly reify mark deleted [
90 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\safe-buffer'
90 silly reify ]
91 silly reify mark deleted [
91 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\setimmediate'
91 silly reify ]
92 silly reify mark deleted [
92 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\string_decoder'
92 silly reify ]
93 silly reify mark deleted [
93 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\supports-color'
93 silly reify ]
94 silly reify mark deleted [
94 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\tmp'
94 silly reify ]
95 silly reify mark deleted [
95 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\command-exists'
95 silly reify ]
96 silly reify mark deleted [
96 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\unzipper'
96 silly reify ]
97 silly reify mark deleted [
97 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\traverse'
97 silly reify ]
98 silly reify mark deleted [
98 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\util-deprecate'
98 silly reify ]
99 silly reify mark deleted [
99 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\wrappy'
99 silly reify ]
100 silly reify mark deleted [
100 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\@types\\color-name'
100 silly reify ]
101 silly reify mark deleted [
101 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\duplexer2'
101 silly reify ]
102 silly reify mark deleted [
102 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\fstream\\node_modules\\rimraf',
102 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\fstream\\node_modules\\.bin\\rimraf',
102 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\fstream\\node_modules\\.bin\\rimraf.cmd',
102 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\fstream\\node_modules\\.bin\\rimraf.ps1'
102 silly reify ]
103 silly reify mark deleted [
103 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\tmp\\node_modules\\rimraf',
103 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\tmp\\node_modules\\.bin\\rimraf',
103 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\tmp\\node_modules\\.bin\\rimraf.cmd',
103 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\node_modules\\tmp\\node_modules\\.bin\\rimraf.ps1'
103 silly reify ]
104 timing reify:diffTrees Completed in 227ms
105 silly reify mark retired [
105 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools',
105 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\func',
105 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\func.cmd',
105 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\func.ps1',
105 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\azfun',
105 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\azfun.cmd',
105 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\azfun.ps1',
105 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\azurefunctions',
105 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\azurefunctions.cmd',
105 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\azurefunctions.ps1'
105 silly reify ]
106 silly reify moves {
106 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools': 'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\.azure-functions-core-tools-3Aw34or4',
106 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\func': 'C:\\Users\\dev\\AppData\\Roaming\\npm\\.func-rP2hOBic',
106 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\func.cmd': 'C:\\Users\\dev\\AppData\\Roaming\\npm\\.func.cmd-NPM7xCQJ',
106 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\func.ps1': 'C:\\Users\\dev\\AppData\\Roaming\\npm\\.func.ps1-JkCKrJCR',
106 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\azfun': 'C:\\Users\\dev\\AppData\\Roaming\\npm\\.azfun-ACE46OoU',
106 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\azfun.cmd': 'C:\\Users\\dev\\AppData\\Roaming\\npm\\.azfun.cmd-7yN6FanA',
106 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\azfun.ps1': 'C:\\Users\\dev\\AppData\\Roaming\\npm\\.azfun.ps1-S5PfQyof',
106 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\azurefunctions': 'C:\\Users\\dev\\AppData\\Roaming\\npm\\.azurefunctions-37a6tcxk',
106 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\azurefunctions.cmd': 'C:\\Users\\dev\\AppData\\Roaming\\npm\\.azurefunctions.cmd-8ksPkHYu',
106 silly reify   'C:\\Users\\dev\\AppData\\Roaming\\npm\\azurefunctions.ps1': 'C:\\Users\\dev\\AppData\\Roaming\\npm\\.azurefunctions.ps1-Gxg8u9sw'
106 silly reify }
107 timing reify:retireShallow Completed in 175ms
108 timing reify:createSparse Completed in 0ms
109 timing reify:loadBundles Completed in 0ms
110 timing reifyNode:node_modules/azure-functions-core-tools Completed in 97ms
111 timing reify:unpack Completed in 97ms
112 timing reify:unretire Completed in 1ms
113 timing build:queue Completed in 63ms
114 timing build:link:node_modules/azure-functions-core-tools Completed in 18ms
115 timing build:link Completed in 19ms
116 info run azure-functions-core-tools@3.0.3568 postinstall node_modules/azure-functions-core-tools node lib/install.js
117 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 829ms
118 timing auditReport:getReport Completed in 832ms
119 timing auditReport:init Completed in 0ms
120 timing reify:audit Completed in 834ms
121 info run azure-functions-core-tools@3.0.3568 postinstall { code: 1, signal: null }
122 timing reify:rollback:createSparse Completed in 10ms
123 timing reify:rollback:retireShallow Completed in 9ms
124 timing command:install Completed in 9792ms
125 verbose stack Error: command failed
125 verbose stack     at ChildProcess.<anonymous> (C:\Users\dev\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
125 verbose stack     at ChildProcess.emit (events.js:315:20)
125 verbose stack     at maybeClose (internal/child_process.js:1048:16)
125 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
126 verbose pkgid azure-functions-core-tools@3.0.3568
127 verbose cwd C:\Users\dev\AppData\Local\Temp
128 verbose Windows_NT 10.0.19041
129 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "azure-functions-core-tools@3"
130 verbose node v14.15.0
131 verbose npm  v7.9.0
132 error code 1
133 error path C:\Users\dev\AppData\Roaming\npm\node_modules\azure-functions-core-tools
134 error command failed
135 error command C:\WINDOWS\system32\cmd.exe /d /s /c node lib/install.js
136 error internal/modules/cjs/loader.js:883
136 error   throw err;
136 error   ^
136 error
136 error Error: Cannot find module 'unzipper'
136 error Require stack:
136 error - C:\Users\dev\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\install.js
136 error     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
136 error     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
136 error     at Module.require (internal/modules/cjs/loader.js:952:19)
136 error     at require (internal/modules/cjs/helpers.js:88:18)
136 error     at Object.<anonymous> (C:\Users\dev\AppData\Roaming\npm\node_modules\azure-functions-core-tools\lib\install.js:3:18)
136 error     at Module._compile (internal/modules/cjs/loader.js:1063:30)
136 error     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
136 error     at Module.load (internal/modules/cjs/loader.js:928:32)
136 error     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
136 error     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
136 error   code: 'MODULE_NOT_FOUND',
136 error   requireStack: [
136 error     'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\azure-functions-core-tools\\lib\\install.js'
136 error   ]
136 error }
137 verbose exit 1
